CLUSTAL W (1.7) multiple sequence alignment


[Pig-tailed_macaca]         -------------------------------------LASSTRARTRRPGLRAVPLPVGR
[Golden_snub-nosed_monkey]  ------------------------------------------------------------
[White-cheeked_gibbon]      ------------------------------------------------------------
[Long-tailed_Macaca]        ------------------------------------------------------------
[Human]                     ------------------------------------------------------------
[Green_Monkey]              MQVPPAPPLRSFTPRGYESATPSPRRYKAAGRPRRARLPSSTRARTRRPGLRAVPLPVGG
[Olive_baboon]              ------------------------------------------------------------


[Pig-tailed_macaca]         FLGKMKWVWALLLLAALGSGRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQ
[Golden_snub-nosed_monkey]  ----MKWMWALLLLAALGSGRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQ
[White-cheeked_gibbon]      ----MKWVWALLLLAALGSGRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQ
[Long-tailed_Macaca]        ----MKWVWALLLLAALGSGRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQ
[Human]                     ----MKWVWALLLLAALGSGRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQ
[Green_Monkey]              FLGKMKWVWALLLLAALGSGRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQ
[Olive_baboon]              ----MKWVWALLLLAALGSGRAERDCRVSSFRVKENFDKARFSGTWYAMAKKDPEGLFLQ


[Pig-tailed_macaca]         DNIVAEFSVDETGQMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASFLQ
[Golden_snub-nosed_monkey]  DNIVAEFSVDETGQMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASFLQ
[White-cheeked_gibbon]      DNIVAEFSVDETGQMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASFLQ
[Long-tailed_Macaca]        DNIVAEFSVDETGQMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASFLQ
[Human]                     DNIVAEFSVDETGQMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASFLQ
[Green_Monkey]              DNIVAEFSVDETGQMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASFLQ
[Olive_baboon]              DNIVAEFSVDETGQMSATAKGRVRLLNNWDVCADMVGTFTDTEDPAKFKMKYWGVASFLQ


[Pig-tailed_macaca]         KGNDDHWIIDTDYDTYAVQYSCRLLNLDGTCADSYSFVFSRDPNGLPPEAQRIVRQRQEE
[Golden_snub-nosed_monkey]  KGNDDHWIIDTDYDTYAVQYSCRLLNLDGTCADSYSFVFSRDPNGLPPEAQKIVRQRQEE
[White-cheeked_gibbon]      KGNDDHWIIDTDYDTYAVQYSCRLLNLDGTCADSYSFVFSRDPNGLPPEAQKIVRQRQEE
[Long-tailed_Macaca]        KGNDDHWIIDTDYDTYAVQYSCRLLNLDGTCADSYSFVFSRDPNGLPPEAQRIVRQRQEE
[Human]                     KGNDDHWIVDTDYDTYAVQYSCRLLNLDGTCADSYSFVFSRDPNGLPPEAQKIVRQRQEE
[Green_Monkey]              KGNDDHWIIDTDYDTYAVQYSCRLLNLDGTCADSYSFVFSRDPNGLPPEAQKIVRQRQEE
[Olive_baboon]              KGNDDHWIIDTDYDTYAVQYSCRLLNLDGTCADSYSFVFSRDPNGLPPEAQKIVRQRQEE


[Pig-tailed_macaca]         LCLARQYRLIVHNGYCDGRSERNLL
[Golden_snub-nosed_monkey]  LCLARQYRLIVHNGYCDGRSERNLL
[White-cheeked_gibbon]      LCLARQYRLIVHNGYCDGRSERNVL
[Long-tailed_Macaca]        LCLARQYRLIVHNGYCDGRSERNLL
[Human]                     LCLARQYRLIVHNGYCDGRSERNLL
[Green_Monkey]              LCLARQYRLIVHNGYCDGRSERNLL
[Olive_baboon]              LCLARQYRLIVHNGYCDGRSERNLL


